baseURL: https://tapanpatro.netlify.app/
languageCode: en-us
theme: charlolamode

title: Tapan Patro
author: Tapan Patro

menu:
    main:
        - name: Contact
          url: /contact/
          weight: 30
        - name: Articles
          url: /articles/
          weight: 20
        - name: Books
          url: /books/
          weight: 20
        - name: Projects
          url: /projects/
          weight: 15
        - name: Me
          url: /me/
          weight: 15

params:
    author: Tapan Patro

    # Theme settings
    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    # SEO enhancements
    metaTags:
        description: "Tapan Patro - Data Scientist Portfolio, showcasing projects, articles, and more."
        keywords: "Tapan Patro, Data Scientist, Portfolio, Projects, Blog"
        twitterCard: "summary_large_image"
        ogImage: "/images/rgb-color-profile.jpg"

    # Custom CSS/JS (if needed)
    customCSS:
        - "/css/custom.css"
    customJS:
        - "/js/custom.js"

    # Profile Mode
    profileMode:
        enabled: true
        title: Tapan Patro
        description: |
          Hello, I am Tapan.
          I am a Data Scientist.
          This is where you can know me better.
        imageUrl: "/images/rgb-color-profile.jpg"
        imageTitle: my image
        buttons:
            - name: Blogs
              url: /articles/
    mainSections:
        - articles

    # Social Icons
    socialIcons:
        - name: buymeacoffee
          url: "https://www.buymeacoffee.com/tapankumar"
        - name: github
          url: "https://github.com/tapankumarpatro"
        - name: linkedin
          url: "https://www.linkedin.com/in/tapankpatro/"
        - name: medium
          url: "https://medium.com/@tapanpatro"
        - name: topmate
          url: "https://topmate.io/tapan_patro/"

    # Favicon and Assets
    assets:
        favicon: "/images/favicon.ico"
        favicon16x16: "/images/favicon-16x16.png"
        favicon32x32: "/images/favicon-32x32.png"
        apple_touch_icon: "/images/apple-touch-icon.png"
        safari_pinned_tab: "/images/apple-touch-icon.png"

# SEO improvements
outputs:
    home: ["HTML", "RSS", "JSON"]
    section: ["HTML", "RSS", "JSON"]
    taxonomy: ["HTML", "RSS", "JSON"]
    taxonomyTerm: ["HTML", "RSS", "JSON"]
    page: ["HTML", "RSS", "JSON"]
    alias: ["HTML"]

# Additional deployment options
deployment:
    targets:
        - name: netlify
          URL: https://api.netlify.com
          headers:
              - for: /images/*
                values:
                    Cache-Control: "public, max-age=31536000, immutable"

# Customizations
markup:
    goldmark:
        renderer:
            unsafe: true

minify:
    disableCSS: false
    disableJS: false
    minifyOutput: true

